### ISSUE TITLE
Case-Sensitivity

### ISSUE THREAD

**Issue by ritvickguptaisb** [athre0z/twocaptcha-api#4]
How to enable case sensitive in twocaptchaapi

**Comment by cptx032** [comment]
@ritvickguptaisb if is not too late...you can do it with:

```python
with open('path-to-my-captcha.png', 'rb') as ff:
    captcha = api.solve(ff, {'regsense': 1})
response = captcha.await_result()
```

The parameters are documented in API page of [2captcha api page](https://2captcha.com/2captcha-api)

**Comment by athre0z** [comment]
Looks like this issue went under my radar. Thanks for taking the time to help with this @cptx032! Given this is now many months old and an issue creator response seems unlikely, I think we can close this as solved for now!
